name: frontend
description: Flutter frontend for WTD - WhatToDo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^4.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  url_launcher: ^6.1.7
  intl: ^0.17.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # If you still have local font files, uncomment and update:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
